# Generated by Django 2.0.6 on 2018-06-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('uiquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentedId', models.IntegerField(default=-1)),
                ('binarySelections', models.CharField(max_length=200)),
                ('numSelected', models.IntegerField(default=-1)),
                ('likert', models.IntegerField(default=-1)),
                ('answeringTimeS', models.IntegerField(default=-1)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiquery.InterviewSession')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('searchEngine', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=200)),
                ('extra', models.CharField(max_length=200)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiquery.Query')),
            ],
        ),
        migrations.RenameModel(
            old_name='RandomisationOrders',
            new_name='RandomisationOrder',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
