# Generated by Django 2.0.6 on 2018-06-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiquery', '0002_auto_20180616_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='orderId',
        ),
        migrations.DeleteModel(
            name='RandomisationOrder',
        ),
    ]
