# Generated by Django 2.0.6 on 2018-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiquery', '0005_auto_20180618_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomisationorder',
            name='manual_id',
            field=models.IntegerField(default=-1),
        ),
    ]
