# Generated by Django 2.0.6 on 2018-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiquery', '0006_randomisationorder_manual_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='participant',
        ),
        migrations.AddField(
            model_name='answer',
            name='randomisationId',
            field=models.IntegerField(default=-1),
        ),
    ]
