# Generated by Django 2.0.6 on 2018-06-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiquery', '0007_auto_20180619_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='query',
        ),
    ]
